### ISSUE TITLE
좋은 자료 감사합니다. 한가지 의견이 있습니다.

### ISSUE THREAD

**Issue by wookho** [kijin/xe-block-search#1]
비회원에게 검색을 제한한다는 것은 회원중심의 사이트를 목표로 하는 곳에서는 아주 유용한 기능이 될 것입니다. 필요한 자원을 회원에게 집중한다는 목적 달성도 되구요.

검색의 불편때문에 회원가입의 유도도 어느정도 기여할 것으로 기대가 됩니다. 

하지만 한가지는 제한에서 풀었으면 하는 바람이 생기네요. 

작성글 보기 <-- 요건 검색기능에 포함된 것이기는 하지만 성격을 약간 다르게 본다면 제외했으면 하는 생각도 들어서요. 

회원의 작성글 보기가 결국 검색어 입력란에 닉네임을 입력하고 검색옵션을 닉네임으로 지정한 검색과 같은 액션일 것입니다. 

하지만 게시판에서 닉네임을 클릭하면 뜨는 레이어에서 이 것을 한번에 작성글 보기 라는 메뉴로 접근이 가능합니다. 

이 기능만 살려두는 것도 필요할 것으로 보여 의견으로 드려봅니다.

저도 이 기능을 동일하게 보아야 하는지 이정도는 열람기회를 줘야 하는건 아니지 하는 판단이 정확하게 서지는 않고 있습니다. 그런데 너무 야박하다는 느낌도 들기도 하구요....   검색창 밖으로 나와있는 기능인데 이게 막히니 좀 그런 생각이 들었습니다.

**Comment by kijin** [comment]
작성 글 보기 기능이 검색 기능의 일부로 포함되어 있는 XE의 이상한 구조 탓이죠...

작성 글 보기만 예외로 하는 것도 어렵지는 않겠지만, 사이트에 따라서는 작성 글 보기도 검색과 마찬가지로 막아야 한다고 생각할 수 있으니 아마 옵션이 되어야 할 것 같네요.

**Comment by wookho** [comment]
네. 옵션을 말씀 드린거에요. 한곳에서 원하는 방향으로 fix 된다면 그게 더 문제가 되겠죠. 저희는 옵션으로 해주시면 아마 작성글 보기는 예외로 할 듯 싶어서요.

**Comment by kijin** [comment]
작성 글 보기 기능만 별도로 허용하는 옵션을 추가했으니 확인 부탁드립니다.

**Comment by wookho** [comment]
감사합니다. 저희 사이트에 해당 옵션 적용하여 작성글보기와 검색에서 닉네임으로 검색까지 잘 작동됩니다. 좋은자료 감사히 잘 쓰겠습니다.
