### ISSUE TITLE
구글 검색봇들 봇은 막지 않도록 할수 있을까요?

### ISSUE THREAD

**Issue by socialskyo** [kijin/xe-block-search#2]
구글 서치 콘솔에서 크롤링 오류에서 보면

search result 에 대한 오류로 아래와 같이 나옵니다.
"서버가 페이지 액세스를 위한 인증을 요구하거나 Googlebot이 사이트에 액세스하지 못하도록 차단하고 있어서 Googlebot이 URL을 크롤링하지 못했습니다. 자세히 알아보기"

흠...권한을 얻어오는 애드온 구조상 아무래도 힘들겠죠??

**Comment by kijin** [comment]
게시판 검색 기능 사용을 막을 뿐, 개별 문서에 직접 접근하는 것은 막지 않으므로 구글 검색순위에 영향을 주지는 않을 것으로 보입니다.

검색 기능 사용을 허락하더라도 결국 개별 문서 페이지로 연결되는 것은 마찬가지여서, 기껏해야 중복 링크나 잔뜩 나올 테니까요.

스킨을 수정해서 비회원에게는 아예 검색창이 표시되지 않도록 해버리면 구글도 더이상 신경쓰지 않습니다.

그리고 구글봇이 검색 기능을 사용하면 서버 부하가 어마어마하게 올라갑니다. 사실 비회원보다도 구글봇을 막으려고 만든 애드온이예요 ㅋㅋ

**Comment by socialskyo** [comment]
@kijin 오호 그런 사실이~~ 그렇군요~ 시원한 답변 감사드려요~
